M48
; DRILL file {KiCad 8.0.1} date 2026-03-25T10:58:13+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-25T10:58:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2067
%
G90
G05
T1
X2.3583Y-3.8379
X2.5866Y-3.8379
T2
X5.8425Y-2.6969
X5.8425Y-3.3661
M30
